# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tanzim Hossain Romel's Portfolio
description: Personal Academic Homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thromel.github.io" # the base hostname & protocol
lang: en

permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"

collections:
  news:
    output: true
    permalink: /news/:path/
  posts:
    output: true
  publications:
    output: true
  showcase:
    output: true

# Build settings
markdown: kramdown
highlighter: rouge

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
      start_line: 1

# Rouge settings
rouge:
  default_lang: python
  css_class: 'highlight'

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-paginate
  - jekyll-analytics

# Analytics Configuration
jekyll_analytics:
  GoogleAnalytics:          # Add your Google Analytics ID here (e.g., 'G-XXXXXXXXXX' for GA4 or 'UA-XXXXXXXX-X' for Universal Analytics)
    id: 'G-P0TDZ6WNVT'       # Replace with your Google Analytics tracking ID
    anonymize_ip: false     # Optional: set to true to anonymize IP addresses
  Matomo:                   # Optional: Matomo (formerly Piwik) analytics
    url: ''                 # Replace with your Matomo URL (e.g., 'https://analytics.example.com')
    site_id: ''             # Replace with your Matomo site ID
  Plausible:                # Optional: Plausible analytics
    domain: ''              # Replace with your domain (e.g., 'example.com')
    source: ''              # Replace with your Plausible source URL (e.g., 'https://plausible.io/js/script.js')

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "showcase"
    values:
      layout: "showcase"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# timezone: Asia/Shanghai
