name: Compile CV to PDF

on:
  push:
    paths:
      - '_posts/cv.tex'
      - '.github/workflows/compile-cv.yml'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          working_directory: _posts
          
      - name: Move PDF to assets
        run: |
          mkdir -p assets/pdf
          mv _posts/cv.pdf assets/pdf/cv.pdf
          
      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/pdf/cv.pdf
          git diff --quiet && git diff --staged --quiet || git commit -m "Update CV PDF"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}